[tracer]
type = "mcpt"
min_depth = 2
max_depth = 6

[image]
width = 1024
height = 768

[sampler]
type = "Stratified"
samples_per_pixel = 16384
x_strata = 128
y_strata = 128

[post_processing]
tone_mapping = "reinhard"
gamma_correction = true

[performance]
parallelism = 0
