[camera]
type = "Perspective"
look_from = { x = 50.0, y = 52.0, z = 295.6 }
look_at = { x = 50.0, y = 39.4, z = 0.0 }
vup = { x = 0.0, y = 1.0, z = 0.0 }
vfov = 30.0
aspect = 1.33

[[objects]]
type = "Sphere"
center = { x = 50.0, y = 681.33, z = 81.6 }
radius = 600.0
[objects.material]
type = "Emissive"
color = { x = 12.0, y = 12.0, z = 12.0 }

[[objects]]
type = "Plane"
point = { x = 1.0, y = 40.8, z = 81.6 }
normal = { x = 1.0, y = 0.0, z = 0.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.75, y = 0.25, z = 0.25 }

[[objects]]
type = "Plane"
point = { x = 99.0, y = 40.8, z = 81.6 }
normal = { x = -1.0, y = 0.0, z = 0.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.25, y = 0.25, z = 0.75 }

[[objects]]
type = "Plane"
point = { x = 50.0, y = 40.8, z = 0.0 }
normal = { x = 0.0, y = 0.0, z = 1.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.75, y = 0.75, z = 0.75 }

[[objects]]
type = "Plane"
point = { x = 50.0, y = 40.8, z = 300.0 }
normal = { x = 0.0, y = 0.0, z = -1.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.75, y = 0.75, z = 0.75 }

[[objects]]
type = "Plane"
point = { x = 50.0, y = 0.0, z = 81.6 }
normal = { x = 0.0, y = 1.0, z = 0.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.75, y = 0.75, z = 0.75 }

[[objects]]
type = "Plane"
point = { x = 50.0, y = 81.6, z = 81.6 }
normal = { x = 0.0, y = -1.0, z = 0.0 }
[objects.material]
type = "Lambertian"
albedo = { x = 0.75, y = 0.75, z = 0.75 }

[[objects]]
type = "Sphere"
center = { x = 27.0, y = 16.5, z = 47.0 }
radius = 16.5
[objects.material]
type = "IdealReflector"

[[objects]]
type = "Sphere"
center = { x = 73.0, y = 16.5, z = 78.0 }
radius = 16.5
[objects.material]
type = "IdealDielectric"
ior = 1.5
