[tracer]
type = "mcpt"
min_depth = 2
max_depth = 6

[image]
width = 500
height = 500

[sampler]
type = "Stratified"
samples_per_pixel = 1024
x_strata = 32
y_strata = 32

[post_processing]
tone_mapping = "reinhard"
gamma_correction = true

[performance]
parallelism = 0
