[image]
width = 500
height = 500

[sampler]
type = "Stratified"
samples_per_pixel = 64
x_strata = 8
y_strata = 8

[post_processing]
tone_mapping = "reinhard"
gamma_correction = true

[performance]
parallelism = 0
