tasks:
- name: "smallpt"
  scene_config: "configs/smallpt/scene.toml"
  render_configs:
  - "configs/smallpt/render_low_quality.toml"
  # - "configs/smallpt/render_medium_quality.toml"
  # - "configs/smallpt/render_high_quality.toml"
